### ISSUE TITLE
Rate limiting and progress bar don't work with FLV files

### ISSUE THREAD

**Issue by theastropath** [porjo/youtubeuploader#95]
OBS Studio generates FLV files when recording which contain H264 video and AAC audio - These upload to Youtube just fine via the web interface (As a baseline "yes, this works).

Using youtubeuploader, these also upload perfectly fine, but you don't get the progress bar during the upload and the rate limiter doesn't appear to actually function (It just uploads at full speed).

If I remux the video into an MP4 container (Without actually changing the encoding of the contents), I get the progress bar and the rate limiter works

**Comment by porjo** [comment]
I just tried uploading an FLV file and it showed progress indicator, and ratelimit was observed. Youtubeuploader just handles binary data, so it doesn't make sense that behaviour would change due to difference in container type. What size is your FLV file?

**Comment by theastropath** [comment]
The file I'm testing with is 430 MB, but the file I originally noticed with was about 7 GB.  I had also been uploading from an NFS share, but I also tried moving the file locally and that didn't change anything.

Is there any debugging I could enable or add (I built from source rather than using the prebuilt versions)?

**Comment by porjo** [comment]
When you say "you don't get the progress bar during the upload" do you mean you don't see the line starting with 'Progress:'  or you see the line, but the values don't change? Could you attach a screenshot?

**Comment by theastropath** [comment]
The line that says progress doesn't show up at all.  Here's a screenshot I just took to demonstrate.  I also included another window over top running nload to show network usage - You can see that it is capping out at my upload limit of 20 Mbps instead of the specified 7500 Kbps

![image](https://user-images.githubusercontent.com/13684088/108643527-ea41a400-7478-11eb-90f9-df4d7ddda98f.png)

**Comment by porjo** [comment]
Thanks. Have you tried the latest pre-built version? If not, please try that.

**Comment by theastropath** [comment]
Unfortunately I can't run the prebuilt version as it requires GLIBC 2.32 and my system only has 2.31 (Ubuntu 20.04)

**Comment by porjo** [comment]
I just pushed a new build for Linux amd64 (x86_64) that doesn't depend on Glibc. Could you try that? https://github.com/porjo/youtubeuploader/releases/download/21.03/youtubeuploader_linux_amd64.tar.gz

**Comment by theastropath** [comment]
I've just tried with that version and still no difference.

**Comment by porjo** [comment]
ok, that's very weird. I notice from your screenshot 'gogoVm' - is that a virtual machine? Can you tell me more about the VM environment?

**Comment by theastropath** [comment]
It's an Ubuntu 20.04 host on an ESXi server.  I doubt that is the issue though.

I was experimenting a bit this evening and think it might be file size related - An ~10 MB video shows the progress bar during an upload, while an ~105MB video does not.  I can share a copy of the larger video if you'd like to see if you can reproduce the issue on your side.

**Comment by theastropath** [comment]
OK, I've burnt through my quota for today trying to narrow down filesizes and got to the point of having a ~15MB file that DID get a progress bar/rate limiting, and a ~20 MB file that did NOT.  Both files were created the same way, and both have the same stream ordering (So that theory that I mentioned in the last comment is out the window).  I can provide both files for your debugging if you'd like.

The other factor which may play into this (But I no longer have the quota to try today) is that /mnt/Storage is an NFS mount, so perhaps that is involved in the different behaviour also.

**Comment by porjo** [comment]
Thanks for the testing. I've pushed another release which I think fixes the issue - please try https://github.com/porjo/youtubeuploader/releases/download/21.04/youtubeuploader_linux_amd64.tar.gz

**Comment by theastropath** [comment]
Partial success!

I did get the progress bar, but it didn't seem to be accurate.  The rate limiter also didn't seem to be working.
![image](https://user-images.githubusercontent.com/13684088/109421117-ff03c780-79a3-11eb-81a7-b48176e91909.png)

Even after the upload finished, the progress bar still showed 0%
![image](https://user-images.githubusercontent.com/13684088/109421146-22c70d80-79a4-11eb-9166-be924efb4e59.png)

**Comment by porjo** [comment]
ok, thanks again for the testing - that's very helpful. More testing of the code that handles progress/limiting is obviously needed. Unfortunately I don't have as much time as I'd like for doing that kind of thing these days. I will get to it when I can, or someone can send a PR.

**Comment by porjo** [comment]
I'll track the progress bar issue in #136
